--Problem 12
--
--The sequence of triangle numbers is generated by adding the natural numbers. 
--So the 7th triangle number would be 
--  1 + 2 + 3 + 4 + 5 + 6 + 7 = 28. The first ten terms would be:
--
--  1, 3, 6, 10, 15, 21, 28, 36, 45, 55, ...
--
--  What is the value of the first triangle number to have over five
--  hundred divisors?


euler12 = head $ dropWhile (\n -> divisorCount n <= 500) triangleNumbers

triangleNumbers :: [Int]
triangleNumbers = scanl (+) (1) [2,3..]

divisorCount n 
    | n == 1    = 1
    | otherwise = 2 * (length $ factorPairs n)


factorPairs :: Int -> [(Int, Int)]
factorPairs x = [ (y, x `div` y) | y <- [1..truncate (sqrt (fromIntegral x))], x `mod` y == 0]

