-- Problem 32 
--
-- We shall say that an n-digit number is pandigital if it makes use of all
-- the digits 1 to n exactly once; for example, the 5-digit number, 15234,
-- is 1 through 5 pandigital.
--
-- The product 7254 is unusual, as the identity, 39 × 186 = 7254,
-- containing multiplicand, multiplier, and product is 1 through
-- 9 pandigital.
--
-- Find the sum of all products whose multiplicand/multiplier/product
-- identity can be written as a 1 through 9 pandigital.
-- HINT: Some products can be obtained in more than one way so be sure to
-- only include it once in your sum.

import Data.List

-- 9 digit pandigital only generated by 2 x 3 digit numbers and
-- 1 x 4 digit numbers

euler32 = sum $ nub $ get1By4 ++ get2By3
    where get1By4 = getPandigital9 [1..9] [1000..9999]
          get2By3 = getPandigital9 [10..99] [100..999]

getPandigital9 xs ys = [x * y | x <- xs, y <- ys, isPandigital x y]

isPandigital x y = allDigits == nub allDigits
                && length allDigits == 9
    where 
          allDigits = (digitsP ++ digitsX ++ digitsY)
          digitsP = digits (x * y)
          digitsX = digits x
          digitsY = digits y

-- Obtain digits from number until 0 is reached or end of number
digits :: Int -> [Int]
digits n = takeWhile (> 0) $ map (`mod` 10) $ iterate (`div` 10) n
